---

- name: Force systemd to reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch.service
    enabled: true 


- name: Start service elasticsearch
  become_method: sudo
  service: 
    name: elasticsearch.service
    state: started
    enabled: yes
  